compliance: fix clap parser crash
```
BRM42220023-switch # swadm compliance ports power --help

thread 'main' panicked at /home/trey/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap-2.34.0/src/app/parser.rs:636:21:
Found positional argument which is not required with a lower index than a required positional argument: "pattern" index 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort (core dumped)
```

Signed-off-by: Trey Aspelund <trey@oxidecomputer.com>